### ISSUE TITLE
请问这个文件是什么？

### ISSUE THREAD

**Issue by yiyi123123132** [WeKnowG/Extractor#2]
def setup(self, model):    
      
        bert_config_path = config.pretrained_model_path + config.MODEL_PATH_MAP[model] + "/config.json" 
        bert_model_path = config.pretrained_model_path + config.MODEL_PATH_MAP[model] + "/model.bin"
        bert_vocab_path = config.pretrained_model_path + config.MODEL_PATH_MAP[model] + "/vocab.txt

这句当中的model.bin，原作者论文的bert文件里面没有这个文件，其他两个文件就同原作者的文件吗？

**Comment by yiyi123123132** [comment]
原作者的bert文件中的bert_config.json 是否对应您的模型中的config.json?

**Comment by caoxu915683474** [comment]
是的
