### ISSUE TITLE
关于复现模型的两个问题

### ISSUE THREAD

**Issue by ISGuXing** [WeKnowG/Extractor#3]
在原论文中训练object模型好像使用的是subject模型预测出来的subjects作为object模型的输入，但是我看您在复现的时候好像不是用预测出来的subjects，而是使用训练集中标注好的subjects？
原论文中说在训练object模型时，需要循环batch中的每个subject来预测object，但是我看您的代码好像并没有循环？
期待您的解答

**Comment by caoxu915683474** [comment]
1 训练时

头实体预测：所有头实体参与训练

关系及尾实体预测： 随机sample出一个头实体参与训练

两个任务损失函数相加

2 推断时

先预测头实体，产生一个预测结果列表

将列表头实体挨个丢入关系及尾实体预测模型，预测尾实体和关系

**Comment by caoxu915683474** [comment]
> 原论文中说在训练object模型时，需要循环batch中的每个subject来预测object，但是我看您的代码好像并没有循环？

请看 extract_items 函数


def extract_items(lm_model, subject_model, object_model, tokenizer, text_in, id2rel, h_bar=0.5, t_bar=0.5):

**Comment by ISGuXing** [comment]
非常感谢您的回答，请问您自己在NYT上测试F1值有多大呢？我自己又动手复现了一下跑了34个epoch，F1只有0.84，唯一的超参数不同就是batch_size我设置了32。

**Comment by caoxu915683474** [comment]
我的这个代码，BERT的调用方法不太对，你可以直接把BERT不包装直接用，F1 用BERT可以达到89%+，如果用SpanBERT可以到91%

**Comment by ISGuXing** [comment]
@caoxu915683474 好的，非常感谢！

**Comment by YuqiChen4188** [comment]
> 我的这个代码，BERT的调用方法不太对，你可以直接把BERT不包装直接用，F1 用BERT可以达到89%+，如果用SpanBERT可以到91%

您在源代码中调整了哪里使得有结果呢  ？
我尝试在代码中训练NYT数据集 但是一直无法预测出结果
